
        const prompts = [
           "A dancing robot with a tutu",
    "A hungry dinosaur eating spaghetti",
    "A flying hamburger with wings",
    "A sleepy lion wearing pajamas",
    "A grumpy cat holding an umbrella",
    "A unicorn jumping over a rainbow",
    "A squirrel playing the trumpet",
    "A penguin doing a cartwheel",
    "A dancing cactus in a cowboy hat",
    "A dragon flying through a donut",
    "A happy whale with a party hat",
    "A giraffe riding a skateboard",
    "A purple octopus wearing sunglasses",
    "A ninja turtle juggling bananas",
    "A flamingo doing yoga",
    "A snail with a rocket backpack",
    "A kitten painting a picture",
    "A dancing pancake with syrup",
    "A turtle playing a guitar",
    "A moon made of cheese with a smiling face",
    "A crocodile wearing a bow tie",
    "A unicorn eating ice cream",
    "A cloud holding a balloon",
    "A monster in a tutu skipping rope",
    "A robot riding a bicycle",
    "A jellyfish playing soccer",
    "A frog in a hammock with sunglasses",
    "A koala wearing a crown",
    "A mouse flying a kite",
    "A penguin wearing a top hat",
    "A bunny juggling carrots",
    "A cat on a skateboard",
    "A rainbow-colored lion with glasses",
    "A giraffe painting a rainbow",
    "A ghost with a big smile",
    "A snowman wearing a tutu",
    "A rocket-powered apple",
    "A dragon wearing a knight’s armor",
    "A dog in a superhero cape",
    "A penguin on a pogo stick",
    "A smiling tree with a party hat",
    "A frog with a guitar",
    "A flying taco with a cape",
    "A sloth playing video games",
    "A tiny elephant on a bicycle",
    "A pizza slice doing a dance",
    "A jellybean flying in a spaceship",
    "A penguin in a tutu with a basketball",
    "A squirrel riding a scooter",
    "A hamster surfing on a wave",
    "A lion wearing a detective hat",
    "A dragon eating a giant cupcake",
    "A rainbow-colored shark with a crown",
    "A superhero cat saving the day",
    "A giraffe wearing a backpack",
    "A dog in a swimming pool",
    "A butterfly with giant glasses",
    "A hedgehog playing basketball",
    "A cupcake with arms and legs",
    "A cat riding a unicorn",
    "A jellyfish with a top hat",
    "A lion with a soccer ball",
    "A pumpkin wearing sunglasses",
    "A dragon with a giant ice cream cone",
    "A dancing potato in a tutu",
    "A frog playing the drums",
    "A pig on a pogo stick",
    "A cow jumping over the moon",
    "A donut playing basketball",
    "A fish wearing a snorkel",
    "A rainbow-colored raccoon",
    "A sheep doing a dance",
    "A flamingo wearing a crown",
    "A snail with a jetpack",
    "A fox in a magician’s hat",
    "A watermelon surfing on the beach",
    "A bat flying with a cape",
    "A carrot with arms and legs playing football",
    "A turtle wearing a jetpack",
    "A unicorn riding a skateboard",
    "A dragon making pizza",
    "A jellyfish riding a scooter",
    "A panda with a rainbow umbrella",
    "A kangaroo in a business suit",
    "A panda flying a kite",
    "A frog wearing a monocle",
    "A puppy riding a rocket",
    "A moose with a party hat",
    "A bunny riding a scooter",
    "A cat baking cupcakes",
    "A dinosaur in a pool floatie",
    "A cat playing a saxophone",
    "A flying pig with a tiara",
    "A hippo wearing a tutu",
    "A dragon with a big teddy bear",
    "A robot walking a dog",
    "A pumpkin on a skateboard",
    "A butterfly with a superhero cape",
    "A sheep on a trampoline",
    "A monster riding a bicycle",
    "A squirrel with a superhero cape",
    "A fish wearing a top hat",
    "A dog with wings and a wand",
    "A monkey on a trampoline with balloons",
    "A flamingo with rainbow-colored feathers",
    "A dancing taco with a bow tie",
    "A flying elephant with a parachute",
    "A sleepy bear holding a coffee cup",
    "A bat with a cape and a sword",
    "A jumping frog with a crown",
    "A purple whale swimming through clouds",
    "A giraffe wearing roller skates",
    "A rabbit in a magician’s costume",
    "A cat riding a skateboard in a circus",
    "A smiling snail with a backpack",
    "A giant pizza slice with sunglasses",
    "A penguin riding a scooter with a scarf",
    "A sloth wearing a business suit",
    "A pink dragon blowing bubbles",
    "A dancing shark with a beach ball",
    "A crocodile playing soccer in a tuxedo",
    "A jellyfish with glasses and a bowtie",
    "A happy koala riding a bike",
    "A dinosaur playing basketball with a crown",
    "A sheep with a party hat and balloons",
    "A monkey wearing a chef’s hat",
    "A unicorn playing hopscotch",
    "A superhero cat with a cape and glasses",
    "A flying giraffe with a balloon",
    "A dog eating spaghetti with a spoon",
    "A bunny with rainbow-colored ears",
    "A frog wearing a flower crown",
    "A fish wearing roller skates",
    "A watermelon on a skateboard",
    "A giraffe with a scarf flying a kite",
    "A dragon wearing a chef’s hat",
    "A flamingo surfing on a wave",
    "A robot making cupcakes",
    "A turtle in a superhero costume",
    "A fox playing the violin",
    "A pig wearing a detective hat",
    "A monster with a crown",
    "A dancing penguin in a tuxedo",
        ];

        let history = [];
        let currentIndex = -1;

        const promptBox = document.getElementById('promptBox');
        const promptButton = document.getElementById('promptButton');
        const previousButton = document.getElementById('previousButton');
        const nextButton = document.getElementById('nextButton');

        promptButton.addEventListener('click', () => {
            const newPrompt = prompts[Math.floor(Math.random() * prompts.length)];
            history.push(newPrompt);
            currentIndex = history.length - 1;
            promptBox.textContent = newPrompt;
        });

        previousButton.addEventListener('click', () => {
            if (currentIndex > 0) {
                currentIndex--;
                promptBox.textContent = history[currentIndex];
            }
        });

        nextButton.addEventListener('click', () => {
            if (currentIndex < history.length - 1) {
                currentIndex++;
                promptBox.textContent = history[currentIndex];
            }
        });